"""Ensure Score model has level column

This migration renames the 'level_reached' column to 'level', makes it non-nullable,
adds proper indexing, and ensures timestamp is non-nullable.

Revision ID: 845454af1341
Revises: c3c18341df31
Create Date: 2025-05-03 12:20:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "845454af1341"
down_revision = "c3c18341df31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scores", schema=None) as batch_op:
        # Add the level column with default value for existing rows
        batch_op.add_column(
            sa.Column("level", sa.Integer(), nullable=False, server_default=sa.text("1"))
        )
        # Ensure timestamp is not nullable
        batch_op.alter_column("timestamp", existing_type=sa.DATETIME(), nullable=False)
        # Create indexes for performance
        batch_op.create_index(batch_op.f("ix_scores_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_scores_user_id"), ["user_id"], unique=False)
        # Drop the old level_reached column
        batch_op.drop_column("level_reached")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scores", schema=None) as batch_op:
        # Add the old column back
        batch_op.add_column(
            sa.Column("level_reached", sa.Integer(), nullable=True)
        )
        # Drop indexes
        batch_op.drop_index(batch_op.f("ix_scores_user_id"))
        batch_op.drop_index(batch_op.f("ix_scores_level"))
        # Revert timestamp nullable constraint
        batch_op.alter_column("timestamp", existing_type=sa.DATETIME(), nullable=True)
        # Drop the level column
        batch_op.drop_column("level")

    # ### end Alembic commands ###
